/**
* This is the description for LOGGER API class. This class manages and generates the LOG file structure.
* The log foldes logs is structures by apps name then date then user logs.
* Ecample :
*     logs > admin > 2.13.2017 > internal.log (contains SERVER internal logs)
*
* Server is expecting USER in the header request transaction. Therefor logs are generated by user at a given date
*
* API Library: /utils/logger
*
* This class is working on a REQUEST => RESPONSE approach
*
* @class LOGGER
*
* @author Ahmed Benamrouche
* Date: February 2017
*
* ── Log Level Reference ────────────────────────────────────────────────────────
*  Level 0  TRACE / DEBUG    Verbose step-by-step detail (dev only)
*  Level 1  INFO  / DETAIL   Operational detail (timing, row counts, XML steps)
*  Level 2  WARN             Unexpected but recoverable situations
*  Level 3  ERROR            Failures requiring attention
*
*  ICR_LOG_LEVEL env var controls the minimum level written to file.
*  Recommended values:
*    ICR_LOG_LEVEL=0  — full trace (equivalent to old ICR_DEBUG=1)
*    ICR_LOG_LEVEL=1  — INFO and above
*    ICR_LOG_LEVEL=2  — WARN and above  ← production default
*    ICR_LOG_LEVEL=3  — ERROR only      ← minimum footprint
*
*  ICR_DEBUG=1 overrides ICR_LOG_LEVEL and captures everything (legacy mode).
* ──────────────────────────────────────────────────────────────────────────────
*/

"use strict";

let heap = {
    fs : require('fs-extra'), // File management
    _: require("lodash")
}

// Log truncation settings
const MAX_LOG_MESSAGE_LENGTH = 5000;
const TRUNCATE_PREVIEW_LENGTH = 500; // Characters to show from beginning and end

// ── CHANGE 1: Level threshold ─────────────────────────────────────────────────
// Messages with level < LOG_LEVEL_THRESHOLD are NOT written to file.
// Default: 2 (WARN+ERROR only). Override with ICR_LOG_LEVEL env var.
// ICR_DEBUG=1 bypasses this gate entirely (legacy full-debug mode).
const LOG_LEVEL_THRESHOLD = parseInt(process.env.ICR_LOG_LEVEL ?? '2', 10);

// ── CHANGE 3: Stream cache ─────────────────────────────────────────────────────
// One WriteStream per log file path is kept open and reused across calls.
// This replaces the previous openSync() + appendFileSync() per log call,
// which paid open/close syscall overhead on every single message.
const _streamCache = new Map();

function _getStream(filePath) {
    if (_streamCache.has(filePath)) {
        return _streamCache.get(filePath);
    }
    const stream = heap.fs.createWriteStream(filePath, { flags: 'a', encoding: 'utf8' });
    stream.on('error', err => console.error('[logger] WriteStream error:', filePath, err));
    _streamCache.set(filePath, stream);
    return stream;
}

/**
 * Close and flush all cached WriteStreams.
 * Call on graceful process shutdown (SIGTERM / SIGINT handler).
 */
function closeStreams() {
    for (const [, stream] of _streamCache) {
        stream.end();
    }
    _streamCache.clear();
}
// ─────────────────────────────────────────────────────────────────────────────

function timestampLog() {
    let date = new Date();
    return (date.getMonth() + 1) + '/' + date.getDate() + '/' +
                    date.getFullYear() + " " + date.getHours() + ":" +
                    date.getMinutes() + ":" + date.getSeconds();
}

function folderDateLog() {
    let date = new Date();
    return (date.getMonth() + 1) + '.' + date.getDate() + '.' +
                    date.getFullYear();;
}

function buildLogStructure () {
    let timestamp = folderDateLog();

    if (!heap.fs.existsSync("logs/") ){
        heap.fs.mkdirSync("logs");
    }
    if (!heap.fs.existsSync("logs/admin/") ){
        heap.fs.mkdirSync("logs/admin/");
    }
    if (!heap.fs.existsSync("logs/server/") ){
        heap.fs.mkdirSync("logs/server/");
    }
    if (!heap.fs.existsSync("logs/admin/"+timestamp) ){
        heap.fs.mkdirSync("logs/admin/"+timestamp);
    }
}


function logParam (uniqueId, parameters, username) {
    log(uniqueId,"\r\n", username);
    console.dir(parameters, {showHidden: false, depth: null});;
    logFile(uniqueId, JSON.stringify(parameters) + "\r\n", username);

}

/**
* Truncates a message if it exceeds the maximum length.
* Shows the beginning and end of the message with a truncation indicator.
* Truncation is disabled when ICR_DEBUG=1 (full messages stored for debugging)
*
* @param {String} message - The message to potentially truncate
* @returns {String} - The original or truncated message
*/
function truncateMessage(message) {
    // When ICR_DEBUG is enabled, store full messages (no truncation)
    if (process.env.ICR_DEBUG == 1 || !message || message.length <= MAX_LOG_MESSAGE_LENGTH) {
        return message;
    }

    const beginning = message.substring(0, TRUNCATE_PREVIEW_LENGTH);
    const end = message.substring(message.length - TRUNCATE_PREVIEW_LENGTH);
    const truncatedLength = message.length - (TRUNCATE_PREVIEW_LENGTH * 2);

    return `${beginning}\n\n... [TRUNCATED ${truncatedLength} characters] ...\n\n${end}`;
}

function logFile(uniqueId, message, username) {
    let timestamp = folderDateLog();
    buildLogStructure();

    // Truncate message if too long (unless ICR_DEBUG is enabled)
    let truncatedMessage = truncateMessage(message);

    // ── CHANGE 3: use cached WriteStream instead of openSync per call ─────────
    const filePath = 'logs/admin/' + timestamp + "/" + username + ".log";
    const stream = _getStream(filePath);
    stream.write(truncatedMessage);
    // ─────────────────────────────────────────────────────────────────────────
}


/**
* LOG method description. Log function is the main function, capturing and
* archiving the log message in the file structure and console file
*
* @method log
* @param {Integer} uniqueID represent the logID (equence number) - Reset to 0 if server is restarting
* @param {String} message is the message to be displayed/archived
* @param {String} username is the user requesting the transaction
* @param {Integer} level  0=TRACE, 1=INFO, 2=WARN, 3=ERROR
*
* A log is generated in the server log file and logs folder
*
*/
function log (uniqueId, message, username, level) {

    // ── CHANGE 1: Level gate ──────────────────────────────────────────────────
    // Skip writing to file if the message level is below the configured threshold.
    // ICR_DEBUG=1 bypasses this gate to preserve legacy full-trace behaviour.
    const effectiveLevel = (level !== undefined && level !== null) ? level : 0;
    if (process.env.ICR_DEBUG != 1 && effectiveLevel < LOG_LEVEL_THRESHOLD) {
        return;
    }
    // ─────────────────────────────────────────────────────────────────────────

    let timestamp = timestampLog();
    let printMessage = timestamp + " [" + username + "] " + uniqueId  + ": " + JSON.stringify(message) + '\n';

    if (process.env.ICR_DEBUG ==1) {
        if (level ) {
            if (level === 0 ) {
                console.log(printMessage);
            }
            if (level === 1) {
                console.log(printMessage);
            }
            if (level === 2) {
                // yellow character
                console.log('\x1b[33m%s\x1b[0m',printMessage);
            }
            if (level === 3) {
                // Red and white character
                console.log('\x1b[41m%s\x1b[0m', printMessage);
            }
        }
        else {
            console.log(printMessage);
        }
    }

    logFile(uniqueId, printMessage, username);
    printMessage=null;
    message=null;
};

module.exports.log          = log;
module.exports.closeStreams = closeStreams; // call on process SIGTERM/SIGINT